export type { VenueError, VenueErrorKind } from './domain/errors'
export type { TableShape, VenueTable } from './domain/venue-table'
export type { VenueZone, ZoneKind } from './domain/venue-zone'
export type { Assignment, AutoAssignResult, Occupancy, SeatedGroup } from './domain/seating'
export { TABLE_SHAPES } from './domain/venue-table'
export { ZONE_KINDS } from './domain/venue-zone'
export { autoAssign, canSeat, occupancyOf } from './domain/seating'
export type { SeatedTable, SeatingView } from './application/list-seating'
export type { ElementMove } from './application/move-element'
export type { AutoAssignSummary } from './application/assign-use-cases'
export type { SeatedGroupRow, VenueRepository } from './application/ports'
