export type { CheckinError, CheckinErrorKind } from './domain/errors'
export type { Arrival } from './domain/arrival'
export type { ResolvedArrival } from './domain/conflict'
export type { DoorGroup, DoorTally } from './domain/door-tally'
export { parsePass } from './domain/parse-pass'
export { doorTally } from './domain/door-tally'
export { resolveArrival } from './domain/conflict'
export type { DoorManifest, DoorManifestGroup } from './application/get-door-manifest'
export type { ScanOutcome } from './application/check-in-by-scan'
export type { ArrivalRepository, DoorGroupReader } from './application/ports'
